config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # devise_for :users
  resources :projects 
  # 	resources :reviews
  # end
  root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
   before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit( :email, :password, :current_password, :avatar) }
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    before_filter :require_permission, only: [:edit, :update, :destroy] 
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @stuff = Project.all.order("created_at DESC")
    end
    
    def show
        
    end
    
    def edit
        
    end
    
    def update
        
        if @stuff.update(stuff_params)
			redirect_to project_path(@stuff)
		else
			render 'edit'
	end
    end
    
    def new
        @stuff = current_user.projects.build
    end
    
    def destroy
        @stuff.destroy
        redirect_to root_path
    end
    
    def create
        @stuff = current_user.projects.build(stuff_params)
        
        if @stuff.save
			redirect_to root_path
		else
			render 'new'
	end
    
    end
    
    private
    
    
    def require_permission
        if current_user != Project.find(params[:id]).user
            redirect_to root_path
        end
    end
    
    def stuff_params
        params.require(:project).permit(:title, :description, :author)
    end
    
        def find_book
			@stuff = Project.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  
  <nav class="navbar navbar-default">
    <div class="container">
        
        <div class="navbar-header">
      				<%= link_to "Project Share", root_path, class: "navbar-brand" %>
      	
      	</div>
      	
      	
      <ul class="nav navbar-nav">
				
				
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					<li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
				<% else %>
				  <li><%= link_to "Sign Up", new_user_registration_path %></li>
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
      
      
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
					<li><%= link_to "Add Book", new_project_path %></li>
				<% end %>
      </UL>
      	
      	
    </div>
  </nav>
  
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>  

  <%= yield %>

</body>


</html>

app/views/projects/_form.html.erb
<div>

<%= simple_form_for @stuff do |f| %>
    <%= f.input :title, label: "Project Title" %>
    <%= f.input :description %>
	<%= f.input :author, label: "Colaborators" %>
	<%= f.button :submit %>
<% end %>

</div>

app/views/projects/edit.html.erb
<h>Edit Project</h>

<%= render 'form' %>

app/views/projects/index.html.erb
	<div>

		<% @stuff.each do |book| %>
		  <h2> <%= link_to  book.title, project_path(book) %> </h2>  
		<% end %>

	</div>
	

app/views/projects/new.html.erb
<h1>new Project</h1>

<div class="new-book-form">

		<h1>New Project</h1>

		<%= render 'form' %>

</div>

app/views/projects/show.html.erb
<div class="book-info">

			<h2 ><%= @stuff.title %></h2>
			<h3 > <%= @stuff.author %></h3>
			<p><%= @stuff.description %></p>

</div>

<%= link_to "Back", root_path, class: "btn btn-custom" %>

<% if @stuff.user_id == current_user.id %>
	<%= link_to "Edit", edit_project_path(@stuff), class: "btn btn-custom" %>
	<%= link_to "Delete", project_path(@stuff), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
<% end %>